# Use an official Python runtime as a parent image
ARG PYTHON_VERSION=3.12.5-slim
FROM python:${PYTHON_VERSION}

# Set environment variables to prevent Python from writing pyc files to disc and buffer output
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Create app directory
WORKDIR /app

# Install app dependencies
COPY requirements.txt ./

RUN pip install -r requirements.txt

# Bundle app source
COPY . /app

CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0" ]
