# Use an official Python runtime as a parent image
ARG PYTHON_VERSION=3.12.5-slim
FROM python:${PYTHON_VERSION}

# Set environment variables to prevent Python from writing pyc files to disc and buffer output
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Create app directory
WORKDIR /app

# Install app dependencies
COPY requirements.txt ./

RUN pip3 install -r requirements.txt

EXPOSE 8501

# Bundle app source
COPY . /app

RUN cat <<EOF > /streamlit_cmd.sh
run_args="run \$app_file"
if [[ "\$app_file" = "hello" ]]; then
    run_args="hello"
fi
streamlit \$run_args --server.address=0.0.0.0 --server.baseUrlPath=\$CL_APP_PATH
EOF

CMD ["bash", "-x", "/streamlit_cmd.sh"]
