FROM python:3.12-slim

# Create app directory
WORKDIR /app

# Install app dependencies
COPY requirements.txt ./

RUN pip3 install -r requirements.txt

EXPOSE 8501

# Bundle app source
COPY . /app

RUN cat <<EOF > /streamlit_cmd.sh
run_args="run \$app_file"
if [[ "\$app_file" = "hello" ]]; then
    run_args="hello"
fi
streamlit \$run_args --server.address=0.0.0.0 --server.baseUrlPath=\$CL_APP_PATH
EOF

CMD ["bash", "-x", "/streamlit_cmd.sh"]
